### ISSUE TITLE
DP Optimizer fails with 'dict' object has no attribute 'action' after issue/441 merge

### ISSUE THREAD

**Issue by jackmcintyre** [jackmcintyre/localshift#458]
## Issue Summary

After merging issue/441 (Shared load forecast + SlotBuilder), the inline DP optimizer fails with an AttributeError.

## Error Details

```
Inline DP optimizer failed (non-blocking): 'dict' object has no attribute 'action'
  File "/config/custom_components/localshift/computation_engine.py", line 1193, in _run_dp_optimizer_inline
  File "/config/custom_components/localshift/computation_engine.py", line 1260, in _assign_active_mode
  File "/config/custom_components/localshift/computation_engine_lib/optimizer_shadow_runner.py", line 860, in _derive_runtime_apply_plan
```

## Impact

- **Severity**: Low (non-blocking error)
- Integration continues to function
- Forecast computation succeeds
- Mode decisions work correctly
- Battery controller operates normally

## Context

This error appeared after merging issue/441 which:
- Added load_forecast_slots shared intermediate (#441 Phase 1)
- Replaced legacy slot builder with SlotBuilder class (#444 Phase 2)
- Inlined DP optimizer to eliminate one-cycle lag (#445 Phase 3)

## Likely Cause

API incompatibility between the new SlotBuilder output format and the _derive_runtime_apply_plan function expecting a different data structure.

## Investigation Needed

1. Check SlotBuilder.build_slots() return format
2. Verify _derive_runtime_apply_plan() expects correct input type
3. Ensure slot_metadata.to_parity_dict() provides all required fields

## Workaround

None needed - error is non-blocking and integration functions correctly.
